### ISSUE TITLE
Generate public initializer for shared structs

### ISSUE THREAD

**Issue by samnm** [chinedufn/swift-bridge#100]
When using swift-bridge in a Swift package it is not possible to initialize a shared struct from Swift due to the default initializer being internal.

I believe the only solution for this is to generate an initializer so that we can explicitly mark it as public.

**Comment by chinedufn** [comment]
Ah nice catch.

# Steps to Fix

- Expose a shared struct in our swift package tests https://github.com/chinedufn/swift-bridge/blob/master/SwiftRustIntegrationTestRunner/swift-package-rust-library-fixture/src/lib.rs#L1-L6

- Add a test case that verifies that we can instantiate a shared struct from a Swift Package https://github.com/chinedufn/swift-bridge/blob/91b480250a59fee392b6f74c75682e4ee871bd99/SwiftRustIntegrationTestRunner/swift-package-test-package/Tests/swift-package-test-packageTests/swift_package_test_packageTests.swift#L6-L8

- Run tests using `./test-integration.sh`

- Tests will fail

- Add `public` to `crates/swift-bridge-ir` to make tests pass

**Comment by samnm** [comment]
Wow that is incredibly helpful thank you. I will give it a shot today!
