### ISSUE TITLE
Running Swift From Rust

### ISSUE THREAD

**Issue by lorenzolewis** [chinedufn/swift-bridge#103]
This could just me missing some basic things, but I wasn't able to find in the book how to compile swift code to link and use in Rust. The book seems to focus heavily on calling Rust FROM Swift but not the other way around.

I'm currently going down the route to use a Swift Package (code is here https://github.com/lorenzolewis/tauri-ffi/tree/main/examples/swift-bridge/src-swift) to hold my Swift code. I don't see anything in the docs on how you're supposed to annotate Swift code to be exposed to Rust so I'm annotating functions with `_cdecl` which I've used from another implementation to text. 

On the Rust side I'm using Tauri and have the Rust code here https://github.com/lorenzolewis/tauri-ffi/tree/main/examples/swift-bridge/src-tauri.

I'm assuming there's some sort of build/compile step I'm missing with Swift to generate the needed header files that I may have just missed in the docs?

**Comment by chinedufn** [comment]
Hey very sorry for the delay, July 21-Aug 1 is super hectic for me and then I'll be back to normal once I settle back in.

---

> The book seems to focus heavily on calling Rust FROM Swift but not the other way around.

Yup totally. The reason for this is that my current use case mainly involves calling Rust from Swift, so I've mainly focused on supporting and writing documentation for that use case.

That being said we also want `swift-bridge` to make it easy to call Swift from Rust so I'd love to help with anything that you need here.

---

So you're trying to compile a Swift native library and then link to it from Rust?

If so, there's a very tiny example of this in the book right now (we still need to write a deeper walkthrough) https://github.com/chinedufn/swift-bridge/blob/a78e617ffbb9471224c4ee79a6e42f0498ed4c43/book/src/building/swiftc-and-cargo/README.md#rust-links-to-a-swift-native-library

---

You don't need to annotate Swift code to call it from Rust. `swift-bridge` generates the FFI bridge for you.

For example

https://github.com/chinedufn/swift-bridge/blob/master/crates/swift-bridge-ir/src/codegen/codegen_tests/opaque_swift_type_codegen_tests.rs#L5-L18

https://github.com/chinedufn/swift-bridge/blob/master/crates/swift-bridge-ir/src/codegen/codegen_tests/opaque_swift_type_codegen_tests.rs#L45-L52

---

> I'm assuming there's some sort of build/compile step I'm missing with Swift to generate the needed header files that I may have just missed in the docs?

Yup it's that little blurb from the first link where you use the `swift-bridge` API or CLI to generate the header files. The CLI command doesn't exist yet, but I can add it for you if you need it (or give you step by step instructions on how to do it if you'd like to make a first contribution!)

---

Let me know if that helps. 

I'd love to help make sure that all of your problems get solved here.

Our approach has been to add documentation as we go.. so once we get you sorted out I'll add some docs on this before closing out this issue.

Cheers!

**Comment by chinedufn** [comment]
Notes for myself...

- [ ] We need to add an example of a Rust binary that links to and calls code from a Swift lib. Maybe `examples/rust-binary-calls-swift-library`

**Comment by chinedufn** [comment]
Update: I have a working example. Now I need to clean it up.

**Comment by chinedufn** [comment]
Whipped up an example of a Rust binary that calls a Swift package in https://github.com/chinedufn/swift-bridge/pull/104

You can view the example here -> https://github.com/chinedufn/swift-bridge/tree/23d60feaa0f8e92f2c854d8665868aa5573ef505/examples/rust-binary-calls-swift-package

Please feel free to re-open this if this example isn't enough for your use case.

Cheers!

**Comment by ericmarkmartin** [comment]
Hey, not the OP but I also have questions in this space. If I have

```swift
class Foo {
  var x : Int

  init(x : Int) {
    self.x = x
  }

  struct Bar {
    var y: Int
  }

  func baz(bar: Bar) -> Int {
    return x + bar.y
  }
}
```

and I want to do something like

```swift
let foo = Foo(x: 1)
let bar = Foo.Bar(y: 2)
print("baz: \(foo.baz(bar: bar))")
```

but from rust, how would I write the bindings.

On another note, can I create bindings to access `var`s in swift classes from rust?
