### ISSUE TITLE
Introduce a compile time error when using missing argument in `args_into = (...)` attribute

### ISSUE THREAD

**Issue by chinedufn** [chinedufn/swift-bridge#11]
```rust
#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        // Right now this compiles, but we want to instead get
        // a compile time error saying that `arg_typo` is not an
        // argument.
        #[swift_bridge(args_into = (arg_typo))]
        fn some_function(arg: u8);
    }
}
```

**Comment by chinedufn** [comment]
# Guide

### Add a UI test

We should add a UI test, perhaps called `args-into-argument-not-found.rs` and `args-into-argument-not-found.stderr`

Here's an example of a different UI test:

https://github.com/chinedufn/swift-bridge/blob/6a10cc2d28f07c36c4ade564cc49f4eaeb787eed/crates/swift-bridge-macro/tests/ui/invalid-module-item.rs#L1-L10

https://github.com/chinedufn/swift-bridge/blob/6a10cc2d28f07c36c4ade564cc49f4eaeb787eed/crates/swift-bridge-macro/tests/ui/invalid-module-item.stderr#L1-L11

More UI tests can be found here -> https://github.com/chinedufn/swift-bridge/tree/6a10cc2d28f07c36c4ade564cc49f4eaeb787eed/crates/swift-bridge-macro/tests/ui

Perhaps our args into UI test has a function with one missing arg, and another function with two missing args.

### ParseError

We can add a new `ParseError` variant for this scenario. 
Perhaps something like `ParseError::ArgsIntoArgNotFound { func: ForeignItemFunc, missing_arg: Ident }`

https://github.com/chinedufn/swift-bridge/blob/72e1759e0504e3a5a32587605c98e410f12ea9e7/crates/swift-bridge-ir/src/errors/parse_error.rs#L7-L22

### Get the test passing

We can get the test passing by iterating over the `attributes.args_into` that we parsed and pushing parse errors if the arg doesn't appear in the function's arguments. 
Perhaps here above the `let func = ParsedExternFn {`

https://github.com/chinedufn/swift-bridge/blob/07a15d78782dc371a7d24301ac9625124e42f8d8/crates/swift-bridge-ir/src/parse/parse_extern_mod.rs#L164-L196

**Comment by NiwakaDev** [comment]
Hi, @chinedufn. Can I work on this?

Sorry...Supporting `Vec<String>` is a more difficult issue than I thought. So, I want to work on another issue first to understand the entire project.

**Comment by chinedufn** [comment]
Sure!

**Comment by chinedufn** [comment]
Closed via https://github.com/chinedufn/swift-bridge/pull/145
