### ISSUE TITLE
Return String from swift?

### ISSUE THREAD

**Issue by gmallios** [chinedufn/swift-bridge#118]
I have been trying to return String from swift side but it cannot be converted to RustStr or RustString. Any ideas?

**Comment by chinedufn** [comment]
Ah yes, this isn't supported yet. Closing in favor of https://github.com/chinedufn/swift-bridge/issues/122

**Comment by chinedufn** [comment]
Here's how to solve this https://github.com/chinedufn/swift-bridge/issues/122#issuecomment-1351744496

**Comment by chinedufn** [comment]
Closed via https://github.com/chinedufn/swift-bridge/pull/123

**Comment by chinedufn** [comment]
Available as 0.1.42 https://github.com/chinedufn/swift-bridge/releases/tag/0.1.42
