### ISSUE TITLE
Support `swift_name` attribute on extern "Swift" functions.

### ISSUE THREAD

**Issue by bes** [chinedufn/swift-bridge#122]
Hi! First - thank you for this project! I have successfully called Rust code from Swift!

Unfortunately, I am having some troubles, and I can't figure out how to fix them.

I want to call a Swift function from Rust, but the generated swift code has a compiler error in it.

This is the rust code (snippet)

```rust
#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        // Works, except the function is still called rust_init on the Swift side?
        #[swift_bridge(swift_name = "rustInit")]
        fn init(url: String);
    }

    extern "Swift" {
        // Generates a Swift compiler error
        #[swift_bridge(swift_name = "getAuthToken")]
        fn get_authentication_token() -> String;
    }
}
```

This snippet is generated

```swift
@_cdecl("__swift_bridge__$get_authentication_token")
func __swift_bridge__get_authentication_token () -> RustString {
    { let rustString = getAuthToken().intoRustString(); rustString.isOwned = false; return rustString.ptr }()
}
```

And then I added this function (in the Swift package, as a new file)

```swift
public func getAuthToken() -> String {
    return "token"
}
```

But the generated snippet has these compiler errors: 

* `Method cannot be marked @_cdecl because its result type cannot be represented in Objective-C`
* `Cannot convert return expression of type 'UnsafeMutableRawPointer' to return type 'RustString'`

An additional, minor, problem is that `#[swift_bridge(swift_name = "rustInit")]` doesn't seem to do anything.

What am I doing wrong? Thanks.

**Comment by chinedufn** [comment]
As for the `swift_name`.

We parse it here https://github.com/chinedufn/swift-bridge/blob/3018fc2d051b34ece0f4709d78c7deb9bf4bb01c/crates/swift-bridge-ir/src/parse/parse_extern_mod/function_attributes.rs#L89-L94

But we don't actually use it.

To fix this, we would first add an integration test. We can use the `rust_name` one as inspiration.

https://github.com/chinedufn/swift-bridge/blob/78be911bbefc847a0ce4e7dfdeaf2deda68c408c/crates/swift-integration-tests/src/function_attributes.rs#L7

https://github.com/chinedufn/swift-bridge/blob/ff3852c6198a43ca3550348be04584f4914c9305/crates/swift-integration-tests/src/function_attributes/rust_name.rs#L1-L10

Then we would add a new test to the function attributes codegen test. Here's an example of one https://github.com/chinedufn/swift-bridge/blob/41f93586cf3eb7cbe441e257a464f4136e0ddcbb/crates/swift-bridge-ir/src/codegen/codegen_tests/function_attribute_codegen_tests.rs#L106-L147

**Comment by bes** [comment]
Would I be correct in assuming that I would need to put a function on the Swift Package side inside the `Generated` directory, that is the actual implementation of the function I am referring to?

Something like

SwiftBridgeImpls.swift

```swift
func someFunction() -> String {
    return "TestString"
}
```

If the ffi bridge looks like this:

```rust
#[swift_bridge::bridge]
mod ffi {
    extern "Swift" {
        // If this compiles then we're successfully using the `rust_name` during code generation.
        #[swift_bridge(swift_name = "someFunction")]
        fn some_function() -> String;
    }
}

```

**Comment by chinedufn** [comment]
Yup! You can create a `FunctionAttributes.swift` in here and put your function in it https://github.com/chinedufn/swift-bridge/tree/master/SwiftRustIntegrationTestRunner/SwiftRustIntegrationTestRunner

**Comment by bes** [comment]
I am trying to run the swift tests, which I assume is just `./test-integration.sh` but I am getting loads of compiler errors

```shell
error[E0433]: failed to resolve: use of undeclared type `Vec`
  --> src/std_bridge/rust_vec.rs:27:44
   |
15 | vec_externs!(f32, OptionF32, 0.123);
   | ----------------------------------- in this macro invocation
...
27 |                     Box::into_raw(Box::new(Vec::new()))
   |                                            ^^^ use of undeclared type `Vec`
   |
   = note: this error originates in the macro `vec_externs` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by chinedufn** [comment]
Hmmmm.... Seems like the standard lib is missing for whatever target you're compiling to. 

Can you try `rustup target add x86_64-apple-darwin aarch64-apple-darwin aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim`?

**Comment by chinedufn** [comment]
Closed via #128

**Comment by bes** [comment]
Thank you for guiding me through this. It was a lot of fun! I am trying to find you on Mastodon, but no luck so far. Any other social media where I can follow you for updates?

**Comment by chinedufn** [comment]
I don't have any socials unfortunately, but if you ever need anything feel free to shoot me an email.

Sure thing, thank you for working on it!

**Comment by bes** [comment]
Wise man 👍
