### ISSUE TITLE
Xcode 14: swift package setup doesn't work

### ISSUE THREAD

**Issue by akesson** [chinedufn/swift-bridge#135]
Thanks for creating swift-bridge. It looks like exactly what I need, but Xcode is giving me hell...

I followed the [instructions](https://chinedufn.github.io/swift-bridge/building/swift-packages/index.html) but when trying to run the project I get a build error `No such module 'PolyglotServer'`

When adding the package dependency it ends up show as a folder instead of a swift package. 
<img width="872" alt="Captura de pantalla 2023-01-12 a las 17 02 39" src="https://user-images.githubusercontent.com/1822029/212119365-e5cbfdf7-2f9e-41ca-8abf-61ff160f444a.png">

Using Xcode 14.2 and swift-bridge 0.1.45

**Comment by akesson** [comment]
FYI: I'm on Mac M1.

The Xcode + Cargo instructions are really good. They worked, with one exception, it only works on a real phone. 

Seems like cargo-lipo doesn't build the simulator binaries. 
```
[INFO  cargo_lipo::meta] Will build universal library for ["ios-rust-analyzer"]
[INFO  cargo_lipo::lipo] Building "ios-rust-analyzer" for "aarch64-apple-ios"
   Compiling ios-rust-analyzer v0.1.0 (/Users/hakesson/Developer/evaluate/ios-rust-analyzer)
    Finished dev [unoptimized + debuginfo] target(s) in 4.01s
[INFO  cargo_lipo::lipo] Building "ios-rust-analyzer" for "x86_64-apple-ios"
   Compiling ios-rust-analyzer v0.1.0 (/Users/hakesson/Developer/evaluate/ios-rust-analyzer)
    Finished dev [unoptimized + debuginfo] target(s) in 2.22s
[INFO  cargo_lipo::lipo] Creating universal library for ios-rust-analyzer
```

When trying to run on sim I get:

> In /Users/hakesson/Developer/evaluate/ios-rust-analyzer/target/universal/debug/libios_rust_analyzer.a(ios_rust_analyzer-ec4a45b193521035.103my0zmix07evm9.rcgu.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/hakesson/Developer/evaluate/ios-rust-analyzer/target/universal/debug/libios_rust_analyzer.a' for architecture arm64

**Comment by akesson** [comment]
Did a PR for the simulator/device building: https://github.com/chinedufn/swift-bridge/pull/136

**Comment by chinedufn** [comment]
> I followed the [instructions](https://chinedufn.github.io/swift-bridge/building/swift-packages/index.html) but when trying to run the project I get a build error No such module 'PolyglotServer'

Did you open a `.xcworkspace` or a `.xcproject` in Xcode? I believe you need to open the `.xcworkspace`.
