### ISSUE TITLE
Optimize RustStr's Equatable implementation

### ISSUE THREAD

**Issue by NiwakaDev** [chinedufn/swift-bridge#148]
I want to address the following TODO:

https://github.com/chinedufn/swift-bridge/blob/a11b368bef4ba904c39481d735db537205de29c4/crates/swift-bridge-build/src/generate_core/string.swift#L28-L35

**Comment by chinedufn** [comment]
Awesome! Let me know if you need anything.

**Comment by NiwakaDev** [comment]
To address this issue, I added the following unit test:
```Swift

let hi = create_string("hi").as_str()
let he = create_string("he").as_str()
XCTAssertNotEqual(hi, he)
```

Result: 
<img width="466" alt="スクリーンショット 2023-01-29 9 45 21" src="https://user-images.githubusercontent.com/61189782/215297854-a5c99b6a-7acf-4b4c-ab2a-6a31ce3bba14.png">

`hi` and `he` seem to have the same address. It's strange. I' dont overrwrite `create_string` and `as_str` method, by the way. I just overrwrote RustStr's `==` operator.

**Comment by chinedufn** [comment]
Closed via https://github.com/chinedufn/swift-bridge/pull/151
