### ISSUE TITLE
Aliasing safety

### ISSUE THREAD

**Issue by anforowicz** [chinedufn/swift-bridge#161]
I have a question that isn't answered by the book yet, so let me open an issue to see if the book can be tweaked to cover an answer.  I see that the "Memory Safety" section of the book has a subsection about [lifetimes](https://chinedufn.github.io/swift-bridge/safety/index.html#lifetimes) - is it possible to also cover aliasing safety?

In particular, can you please clarify if/how the FFI layer enforces [aliasing safety](https://doc.rust-lang.org/reference/behavior-considered-undefined.html#:~:text=Breaking%20the%20pointer%20aliasing%20rules.)?  For example, is it possible to call the following function with the same reference passed to both arguments (AFAIK this example can be used to trigger Rust UB by making a [`cxx`](https://cxx.rs/)-mediated call from C++):

```rs
pub fn clone_from_i32(target: &mut i32, source: &i32) {
    // Rust guarantees that `&mut T` is the only, exclusive reference.
    // Having a `&mut T` that is aliased by other references leads to
    // Undefined Behavior in Rust.
    let target_ptr: *mut i32 = target;
    let source_ptr: *const i32 = source;
    assert_ne!(target_ptr.cast_const(), source_ptr);

    target.clone_from(source);
}
```

If it is not possible to cause an aliasing violation, then can you clarify how this is achieved?  Maybe this aspect of safety is already guaranteed by the [runtime exclusivity checks in Swift](https://www.swift.org/blog/swift-5-exclusivity/)?

**Comment by chinedufn** [comment]
At a high level this folds under #162 in that [Rust's borrowing rules](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html#the-rules-of-references) are not currently fully enforced across FFI boundaries.

`swift-bridge` does not currently guarantee aliasing safety. For example, the following is currently possible:

```rust
// Rust

#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        type RustType;

        #[swift_bridge(init)]
        fn new() -> RustType;

        fn combine(a: &mut RustType, b: &RustType);
    }
}
```

```swift
// Swift

let rustType = RustType()

// Violates Rust's borrowing rules.
rustType.combine(rustType)
```

---

Whether or not Swift's upcoming ownership related features will allow us to better enforce Rust's borrowing rules across the FFI boundary is an open question that needs more research.

---

If the `Safety` chapter explained that Rust's borrowing rules are not enforced on the Swift side, would you consider this issue closed?

**Comment by anforowicz** [comment]
> If the Safety chapter explained that Rust's borrowing rules are not enforced on the Swift side, would you consider this issue closed?

Yes, except (IMHO, feel free to disagree) I would separate out discussion and examples of lifetime vs aliasing vs mutability (rather than covering all of them together as borrowing rules).  In other words (again IMHO / from my perspective), I would like to see separate "aliasing" and "mutability" sections (next to the ["lifetimes"](https://chinedufn.github.io/swift-bridge/safety/index.html#lifetimes) section) that 1) say something like "Swift/Rust FFI can trigger Undefined Behavior in Rust, if it creates a situation where Rust's mutable reference is not the only, exclusive reference" and 2) give an example of how that can happen to make it a bit easier for readers to understand what to watch out for (the example in your comment is very nice).

**Comment by chinedufn** [comment]
Closed via https://github.com/chinedufn/swift-bridge/pull/164
