### ISSUE TITLE
Mutability safety

### ISSUE THREAD

**Issue by anforowicz** [chinedufn/swift-bridge#162]
I have a question that isn't answered by the book yet, so let me open an issue to see if the book can be tweaked to cover an answer. I see that the "Memory Safety" section of the book has a subsection about [lifetimes](https://chinedufn.github.io/swift-bridge/safety/index.html#lifetimes) - is it possible to also cover mutability safety?

In particular, if Swift passes an immutable Rust reference (`&T`) into a Rust function, then can Swift mutate the value behind such reference (e.g. if the Rust function calls back into Swift, then can the called back Swift code mutate the value)?  (Rust's language reference [says](https://doc.rust-lang.org/reference/behavior-considered-undefined.html#:~:text=Mutating%20immutable%20data.) that "mutating immutable data" triggers undefined behavior.)

It's possible that this is already taken care of and inherently safe because of Swift and Rust languages design.  If so, then I think it would be great to point that out in the book.

**Comment by chinedufn** [comment]
Thanks a lot for the question and suggestion.

---

If we're only passing around a Rust `&T` then Rust's borrowing rules cannot be broken
since when the Rust `&T` shows up on the Swift side none of `T`'s mutable methods will
be available.

( See: https://github.com/chinedufn/swift-bridge/blob/bdbb028dea65148136851ff24bb8a025c5c66557/book/src/bridge-module/opaque-types/README.md?plain=1#L52-L133 )

```rust
// Rust
#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        type MyGreeter;

        fn new() -> MyGreeter;

        fn greet(&self, user: SomeSwiftUser);
        fn mutate(&mut self);
    }

    extern "Swift" {
        type SomeSwiftUser;

        fn analyze_greeter(&self, greeter: &MyGreeter);
    }
}
```

```swift
// Swift

class SomeSwiftUser {
    func analyze_greeter(greeter: MyGreeterRef) {
        // This `greeter.mutate()` would not compile since
        // it doesn't exist on `MyGreeterRef`.
        // greeter.mutate()
    }
}
```

However, it's totally possible to violate Rust's borrowing rules today.

# Violating Rust's borrowing rules

Here are the two cases that I can think of where you can violate Rust's borrowing rules.

I'm not yet sure to what extent we'll be able to mitigate these as [Swift introduces more ways to enforce ownership.](https://github.com/apple/swift/blob/main/docs/OwnershipManifesto.md).

## Case 1 - Multiple Mutable References

```rust
// Rust
#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        type MyList;

        fn new() -> MyList;

        fn get_mut_ref(&mut self) -> &mut MyList;
    }
}
```

```swift
// Swift

let myList = MyList()

let myListMut1: MyListRefMut = MyList.get_mut_ref()
// Holding two mutable references violates Rust's borrowing rules.
let myListMut2: MyListRefMut = MyList.get_mut_ref()
```

## Case 2 - Mutating during a callback

```rust
// Rust
#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        type MyList;

        fn new() -> MyList;

        fn allegedly_immutable(&self, callback: Box<dyn Fn()>);
        fn mutate(&mut self);
    }
}
```

```swift
// Swift
let myList = MyList()

myList.allegedly_immutable({
    // If the `allegedly_immutable` method calls this
    // callback we will take a mutable reference to `MyList`
    // while there is an active immutable reference.
    // This violates Rust's borrowing rules.
    myList.mutate()
})
```

---

Had some of this information been in the `Safety` chapter (with a bit more prose)
when you read it, would you have any more questions about our mutability safety story?

If so, we can document this.

If not, what do you think is missing?

**Comment by anforowicz** [comment]
Thank you for a prompt reply!  (And thank you for having a separate part of the book dedicated to safety!)

> Had some of this information been in the Safety chapter (with a bit more prose)
when you read it, would you have any more questions about our mutability safety story?

I think this is sufficient information.  At a high-level, I think it is desirable to explicitly communicate what to watch out for (with one audience being 1) Swift / Rust FFI users and a bit different audience of 2) FFI security auditors).  And I think the main message can be quite short - something like: "Swift/Rust FFI can trigger Undefined Behavior in Rust, if Swift mutates a value that Rust's immutable reference refers to" .  And then the example from your "case 2" can illustrate this.

The rest of this comment is a bit nitpicky - feel free to ignore:
- In my mind I see your "case 1" as an example of an aliasing safety violation (rather than mutability safety violation).  OTOH, I am probably making up the terminology here.  I guess that instead of saying "aliasing safety violation" Rust language reference would [say](https://doc.rust-lang.org/reference/behavior-considered-undefined.html#:~:text=Breaking%20the%20pointer%20aliasing%20rules.) "breaking the pointer aliasing rules".
- I am not familiar with Swift language rules, but maybe holding 2 mutable references to the same object is okay in Swift (i.e. as long as they are not passed to Rust)?  It would definitely be Undefined Behavior *after* passing these mutable references to Rust.

**Comment by chinedufn** [comment]
And thank you for opening these issues!

---

> I see your "case 1" as an example of an aliasing safety violation

For sure. I was trying to bubble things up under "Rust's borrowing rules" (I now know that you're suggesting that we shouldn't do that)

> but maybe holding 2 mutable references to the same object is okay in Swift

Yup I'd assume so.

---

Would love for you to review #164 . Let's move the discussion there.

Thank you again!

**Comment by chinedufn** [comment]
Closed via https://github.com/chinedufn/swift-bridge/pull/164
