### ISSUE TITLE
Error while parsing "src/lib.rs"  expected `const` or `mut`

### ISSUE THREAD

**Issue by lockieluke** [chinedufn/swift-bridge#171]
```rust
#[swift_bridge(swift_repr = "struct")]
pub struct DiscordRPCAgent {
    client: Client,
    thread: Option<*Thread>
}
```

I'm trying to use `Option<>` in my struct but it doesn't let me

**Comment by chinedufn** [comment]
Hey.

This is a Rust compile time error, not a `swift-bridge` error.

`*Thread` is invalid Rust syntax.

The Rust compiler is seeing this and suggesting that you might either mean `*const Thread` or `*mut Thread`.

I'm assuming that you don't actually want either of those though.

It seems like you really want `Option<Thread>` (without the `*`)?

**Comment by chinedufn** [comment]
Closing since that should fix it. Feel free to re-open if you still have issues.

Cheers!

**Comment by lockieluke** [comment]
Thanks for the swift reply!
