### ISSUE TITLE
Add compile time error when using `associated_to` on a method

### ISSUE THREAD

**Issue by chinedufn** [chinedufn/swift-bridge#179]
Right now, the following code compiles:

```rust
#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        type SomeType;

        #[swift_bridge(associated_to = SomeType)]
        fn x(&self);
    }
}
```

We do not want this to compile, since `associated_to` is meant for declaring **static** methods.

---

We can make this more clear by:

- Renaming `associated_to` to `static_method_of` (and making sure to update our docs and tests to use the new name)

-  Introducing a compile time error when using `static_method_of` on a method (any function that takes `self`, `&self` or `&mut self`).

We can keep `associated_to` around until version `0.2.0`, just like how we handle `into_return_type` https://github.com/chinedufn/swift-bridge/blob/91b480250a59fee392b6f74c75682e4ee871bd99/crates/swift-bridge-ir/src/parse/parse_extern_mod/function_attributes.rs#L97-L100

**Comment by NiwakaDev** [comment]
I'd like to work on this issue!!

**Comment by chinedufn** [comment]
Go for it!
