### ISSUE TITLE
Replace `ResultVoidAndPtr` with a pointer (null pointer optimization)

### ISSUE THREAD

**Issue by chinedufn** [chinedufn/swift-bridge#183]
Right now we have a `struct ResultVoidAndPtr { is_ok: bool, err: *mut std::ffi::c_void }` type https://github.com/chinedufn/swift-bridge/blob/27d7be991141586fb120e4691b7bea7d9eeecd17/src/std_bridge/result.rs#L48-L55 that is used to encode types like `Result<(), OpaqueType>`.

Say we're bridging `Result<(), OpaqueType>`.

If the pointer is null, we know that it's the `()`. If the pointer is non null, we know that it's the `OpaqueType`.

So, we don't need the `is_ok`. Meaning we don't need a struct at all and can just use `*mut super::OpaqueType`.

---

To fix this, we can replace `ResultVoidAndPtr` in our codegen tests with `*mut super::SomeType`. Then get the tests passing.

https://github.com/chinedufn/swift-bridge/blob/ff19bb86f4271cec3e4558dcf49aaa4a510fc162/crates/swift-bridge-ir/src/codegen/codegen_tests/result_codegen_tests.rs#L267-L406

We can also delete the supporting C type https://github.com/chinedufn/swift-bridge/blob/27d7be991141586fb120e4691b7bea7d9eeecd17/crates/swift-bridge-build/src/generate_core/result_support.rs#L42-L44

---

#### Related

https://github.com/chinedufn/swift-bridge/issues/177
https://github.com/chinedufn/swift-bridge/pull/180
https://github.com/chinedufn/swift-bridge/commit/27d7be991141586fb120e4691b7bea7d9eeecd17#r102860388

**Comment by NiwakaDev** [comment]
If #182 is merged, I'd like to work on this.

**Comment by chinedufn** [comment]
Go for it!

**Comment by chinedufn** [comment]
Closed via https://github.com/chinedufn/swift-bridge/pull/184
