### ISSUE TITLE
Support tuples

### ISSUE THREAD

**Issue by chinedufn** [chinedufn/swift-bridge#188]
For example, the following should be possible:

```rust
#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        fn reflect_tuple(tuple: (u8, u16)) -> (u8, u16);
    }
}
```

```swift
// Swift

let arg = (234, 567)
let tuple: (UInt8, UInt16) = reflect_tuple(arg)
```

**Comment by NiwakaDev** [comment]
What do you think about the following idea?

```rust
//Rust
(u8, u16)
```

the FFI representation of the above tuple:
```rust
struct tupleU8U16(u8, u16)
```

**Comment by chinedufn** [comment]
Yeah that sounds about right.

I think we can re-use the same codegen that powers structs with unnamed fields.

So, the FFI representation and C header codegen would be similar to:

```rust
#[swift_bridge::bridge]
mod ffi {
    struct MyStruct(u8, 16);
}
```

https://github.com/chinedufn/swift-bridge/blob/c1fd7177b5d3a8918e34b6bc96ae29437cfc1487/crates/swift-bridge-ir/src/codegen/codegen_tests/transparent_struct_codegen_tests.rs#L263

---

But we'd want to make sure that if there were two of the same tuple we didn't generate the same C header code twice.

```rust
#[swift_bridge::bridge]
mod ffi {
    // __swift_bridge__$mod_ffi$tuple$u8_u16 gets emitted once in the C header,
    // even thought we use it twice.
    // We include a module name segment `mod_ffi` in the name so that you can prevent the
    // C header types from collide across different bridge modules by giving the modules
    // different names.
    // In the future we might want to consider having `swift-bridge-build` automatically remove duplicate 
    // tuple definitions from the generated C header.
    extern "Rust" {
        fn x() -> (u8, u16);
        fn y() -> (u8, u16);
    }
}
```

**Comment by NiwakaDev** [comment]
I'd like to implement this!! Can I implement this?

**Comment by chinedufn** [comment]
Go for it!!

When you get it working you'll want to add it to the built in types table:

https://github.com/chinedufn/swift-bridge/blob/master/README.md?plain=1#L104-L133

As well as adding it to the built-in types chaoter in the book:

https://github.com/chinedufn/swift-bridge/blob/ef2029a6228ffc850fb9cf317e09b60b17bf0736/book/src/SUMMARY.md?plain=1#L22-L28

**Comment by NiwakaDev** [comment]
I encountered this problem while working on supporting tuples.

**Comment by chinedufn** [comment]
I see. Thanks for the links.

Let's change `SharedStruct. convert_rust_expression_to_ffi_repr` into `SharedStruct.generate_into_ffi_repr_method` and have it produce the entire method, instead of just the body.

https://github.com/chinedufn/swift-bridge/blob/1b33e95b9c5b2d87ca2485aa972dcbb6f971ef18/crates/swift-bridge-ir/src/codegen/generate_rust_tokens/shared_struct.rs#L110-L116

This way the entire `fn into_ffi_repr(self) -> ...` method gets generated in one place.

**Comment by NiwakaDev** [comment]
>Let's change SharedStruct. convert_rust_expression_to_ffi_repr into SharedStruct.generate_into_ffi_repr_method and have it produce the entire fn into_ffi_repr(self) -> ... method, instead of just the body.

Sounds good to me!!

Can I add this change to a PR for supporting tuples? If not, I'll make a trivial PR today or tomorrow.

**Comment by NiwakaDev** [comment]
I think we can close this issue.
