### ISSUE TITLE
Add test code for returning  `Result<transparent struct, transparent struct>`

### ISSUE THREAD

**Issue by NiwakaDev** [chinedufn/swift-bridge#212]
Related to #168.

I found that returning `Result<transparent struct, transparent struct>` works correctly without needing any PRs.

But, I think that we need to add any tests for returning `Result<transparent struct, transparent struct>`.

I guess that the following test codes might be helpful as references.

Codegen Test:
https://github.com/chinedufn/swift-bridge/blob/1f9dd05360b4001fbe4c167304f6815399882699/crates/swift-bridge-ir/src/codegen/codegen_tests/result_codegen_tests.rs#L465-L540

Integration Test:
https://github.com/chinedufn/swift-bridge/blob/1f9dd05360b4001fbe4c167304f6815399882699/SwiftRustIntegrationTestRunner/SwiftRustIntegrationTestRunnerTests/ResultTests.swift#L99-L129

And then we need to update `examples/async-functions/src/lib.rs`:

https://github.com/chinedufn/swift-bridge/blob/1f9dd05360b4001fbe4c167304f6815399882699/examples/async-functions/src/lib.rs#L15-L16

**Comment by chinedufn** [comment]
Thanks for adding a guide!

Should we close this and instead add your guide to #168 ?

As in, maybe move your comment from this PR to #168 ?

hen whenever someone adds a test / updates the example we can close #168 .

**Comment by NiwakaDev** [comment]
Sure. I move this comment to #168 and then close this issue.
