### ISSUE TITLE
Upgrade `swift-bridge` version to incorporate new features.

### ISSUE THREAD

**Issue by NiwakaDev** [chinedufn/swift-bridge#233]
We've implemented the following features, but right now users couldn't use them since `swift-bridge` isn't upgraded yet:

- [Support Rust fn return](https://github.com/chinedufn/swift-bridge/commit/321e03e8d7f51fbf0629f56960defebfced244dc) [Result<enum, enum>](https://github.com/chinedufn/swift-bridge/commit/321e03e8d7f51fbf0629f56960defebfced244dc)
- [Rust async fn return Result<enum, enum>](https://github.com/chinedufn/swift-bridge/commit/68c3a385fcc21810f6f33794fc63003c3b9bb168)
- [Support Rust async fn ret](https://github.com/chinedufn/swift-bridge/commit/2d60d9ee83a153b07c5413af9f9cc3ad6075c9f4) [Result<(),enum>](https://github.com/chinedufn/swift-bridge/commit/2d60d9ee83a153b07c5413af9f9cc3ad6075c9f4)
- [Adding derive() macro support to SharedStructs](https://github.com/chinedufn/swift-bridge/commit/6b151f1ab72fb3f36f61c42186dc3319b17936a9)
- Add Vec<f32> and Vec<f64> support #200
- [Fix dangling pointer warning](https://github.com/chinedufn/swift-bridge/commit/03ca04126a8f73f8208fbee3572ea905e1a93aec)
- [Support Option<Primitive> in Swift fns](https://github.com/chinedufn/swift-bridge/commit/fdca9fcc2080a60d30de958fc4ada2516691581e)
- [Add Performance section to README](https://github.com/chinedufn/swift-bridge/commit/d713d36391a09fedc5c1b03cd3a15c814f2f11ef)
- Support tuples #195
- Support primitive tuples Swift -> Rust #205
- Add compile error for associated_to attribute #206 
- Support derive(Debug) on enums #194 
- Support tuples from Swift -> Rust #211 
- [Add](https://github.com/chinedufn/swift-bridge/commit/7e140ca5e6ec3f969c19001c844f98fe76bd787c) [RustVec<T>.as_ptr](https://github.com/chinedufn/swift-bridge/commit/7e140ca5e6ec3f969c19001c844f98fe76bd787c) method
- [Support returning Result<tuple, Any Type> from Rust](https://github.com/chinedufn/swift-bridge/commit/852ece728d3f362f3ada4368e037fe9ebb2a913f)
- [Fix returning Result<Vec<>, ...> from Rust](https://github.com/chinedufn/swift-bridge/commit/de059024732fa2f8135a9fe1232b727d96794af6)
- [Fix async Rust fn return Result<(), OpaqueType>](https://github.com/chinedufn/swift-bridge/commit/7c14ea07ab71702019e652fcc5a5f7a111d5ea0e)
- [Fix](https://github.com/chinedufn/swift-bridge/commit/ecd3b974754e32fc951b8bc4098ecef84e974821) [already_declared](https://github.com/chinedufn/swift-bridge/commit/ecd3b974754e32fc951b8bc4098ecef84e974821) attribute for enums and structs
- [Swift](https://github.com/chinedufn/swift-bridge/commit/ffe20d8c8eb4f0404e1e56ef3892f810c7182fea) [Vec<primitive>](https://github.com/chinedufn/swift-bridge/commit/ffe20d8c8eb4f0404e1e56ef3892f810c7182fea) [ret type and fn arg](https://github.com/chinedufn/swift-bridge/commit/ffe20d8c8eb4f0404e1e56ef3892f810c7182fea)
- [Add docs on RustString](https://github.com/chinedufn/swift-bridge/commit/36565f2c59b4bc438b54fdf5fb5a696ea63348df)
- [Support](https://github.com/chinedufn/swift-bridge/commit/27246447b4ac741b8bf086d3dfca15b47558e44f) [RustString](https://github.com/chinedufn/swift-bridge/commit/27246447b4ac741b8bf086d3dfca15b47558e44f) in extern Swift functions

**Comment by chinedufn** [comment]
Yeah sorry I procrastinated on this since making the release notes takes some time and isn't automated.

I have an unusually busy weekend so I'll get this done within the next week.

Thanks for opening this issue. We can release more regularly going forward.

**Comment by chinedufn** [comment]
https://github.com/chinedufn/swift-bridge/releases/tag/0.1.52

**Comment by NiwakaDev** [comment]
Thanks a lot!!
