### ISSUE TITLE
Missing `Error` impl for `throw MyError` fn

### ISSUE THREAD

**Issue by boozook** [chinedufn/swift-bridge#298]
The type returned by a function as second part of the `Result` must implement the `Error` protocol. For example:
```rust
struct MyErr;
fn err() -> Result<(), MyErr> { Ok(()) }
fn string() -> Result<(), String> { Ok(()) }

#[swift_bridge::bridge]
mod ffi {
	extern "Rust" {
		type MyErr;

		fn err() -> Result<(), MyErr>;
		fn string() -> Result<(), String>;
	}
}
```
Error: `Thrown expression type 'RustString' does not conform to 'Error'`
Produced Swift:
<img width="1432" alt="Screenshot 2024-11-02 at 12 48 45" src="https://github.com/user-attachments/assets/45fa2e15-ffc4-46e9-998a-d471404d4329">

- - -

Workaround is to add impl by hand:
```swift
extension MyErr: Error {}
extension RustString: Error {}
```
But this is not refactorible and could be great to have one of following options:
- generate `extension {Ty}: Error {}` automatically
- generate `extension {Ty}: Error {}` by rust attribute like `#[swift_bridge(impl(Error))] type MyErr;`
- inject user's raw swift-source into generated output.

First and second are the best, imho.

**Comment by chinedufn** [comment]
Thanks for opening this issue.

---

Support for ` -> Resutlt<*, String>` is implemented and will be available in the next release https://github.com/chinedufn/swift-bridge/pull/296

---

Support for the `Error` protocol is tracked in https://github.com/chinedufn/swift-bridge/issues/150 , so I'll close this in favor of that issue.
If you or any future person that sees this is interested in implementing support for the `Error` protocol I'd be happy to provide hand-held guidance and answer all questions.

**Comment by boozook** [comment]
@chinedufn Thanks! Impl for `String` is good but I need to know is that error recoverable or not, so I need a custom struct.

**Comment by chinedufn** [comment]
Anytime.

#150 would solve your problem., or are you suggesting otherwise?

**Comment by boozook** [comment]
Partially. Could be great to have something like `#[swift_bridge(Sendable, Error)] type Foo;`.

**Comment by boozook** [comment]
> #150 would solve your problem., or are you suggesting otherwise?

Looks like good enough, as I hope. Thanks! 😊
