### ISSUE TITLE
Design question about using a single bridge file vs. in-line annotations

### ISSUE THREAD

**Issue by ryankaplan** [chinedufn/swift-bridge#300]
Hi! First off, thanks for creating Swift-Bridge! I really appreciate your work!

I have a question about the API design for the project. Swift-Bridge requires users to define a `#[swift_bridge::bridge]` module to expose functionality, whereas projects like [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen) allow attributes to be added directly to structs, enums, or functions throughout the codebase.

I’m curious about the reasoning behind this design choice. Is there a technical limitation that prevented you from annotating types in-line? Or did you prefer to have all bindings in a single file?

The reason I ask is that I I have many types throughout my Rust codebase that are exposed transparently to wasm/JS and that I'd like to expose to Swift. They currently live next to the rust code that handles them; I think it'd hurt codebase organization to put them in a single bridge file. I wonder if you've thought about this use case and have any advice.

Looking forward to hearing your thoughts! Thanks again for the amazing work.

Update: I see that maybe the API of swift-bridge is modeled after cxx. If any case I'm curious to know how you feel about the trade-offs between the single-file bridge API vs. inline annotations.

**Comment by chinedufn** [comment]
Hey Ryan.

I've added documentation explaining why we support the bridge module approach: https://github.com/chinedufn/swift-bridge/pull/301

In short, separating bindings from types was a matter of preference.
It also tends towards more efficient code, but for most real-world use cases I'd expect the difference to be meaningless.
All of this is better explained in the new documentation.

---

Please note that it is currently possible to define your FFI boundary across multiple files.

You can use the `#[swift_bridge(already_declared)]` attribute.

https://github.com/chinedufn/swift-bridge/blob/c45a38cf8730013a6a03af2184df0831f523b1a6/book/src/bridge-module/opaque-types/README.md?plain=1#L136-L166

Does that help with your use case?

**Comment by chinedufn** [comment]
Here's an example of using multiple bridge modules: https://github.com/chinedufn/swift-bridge/pull/302

**Comment by ryankaplan** [comment]
Ooh interesting, thank you! Really appreciated reading through the documentation, and while I'd love inline annotations multiple bridge files works fine for me.

**Comment by ryankaplan** [comment]
Ah, I've discovered args_into and return_into. So I can declare transparent enums like FfiEnum and then automate the conversions. Is that the intended happy path?

**Comment by chinedufn** [comment]
Yeah that's one way that `args_into` and `return_into` can be used.

For some use cases you could also consider `use ffi::MyEnum` so that you don't have to duplicate the enum.
I don't personally do that since my application code doesn't know about my bridging layer, but I've seen other open source crates use that pattern.

**Comment by chinedufn** [comment]
Oh I just saw your first comment https://github.com/chinedufn/swift-bridge/issues/300#issuecomment-2501997795

Specifically:

> I'm happy to move them to the bridge file, but when I do they'll no longer be exposed to web.

So, yeah, `args_into` and `return_into` are currently the best way to handle your problem.
