### ISSUE TITLE
Current version usable on M1?

### ISSUE THREAD

**Issue by Maxung** [chinedufn/swift-bridge#39]
I've tried both the book example + running the tests and both fail ("error[E0658]: destructuring assignments are unstable" and "panic in main thread" respectively). Do I need nightly compiler?

I can follow up with stack traces/needed info, if someone could confirm it's buildable/usable. I really like the idea of this crate, so hoping to succeed

**Comment by chinedufn** [comment]
Hey!

The CI test suite runs on stable so that shouldn't be the issue.

https://github.com/chinedufn/swift-bridge/blob/277e0f5ed9ae8e62b73dc2a21d87be4e5e828ecb/.github/workflows/test.yml#L19

---

Mind providing 

1. Your Rust version `rustc -V`
2. Steps to reproduce the issue that you're seeing
3. The stack trace

**Comment by Maxung** [comment]
So as base I'm using the example from the [book](https://chinedufn.github.io/swift-bridge/building/swift-packages/index.html).

```sh
$ mkdir generated
$ export SWIFT_BRIDGE_OUT_DIR="$(pwd)/generated"
$ cargo build
$ swift-bridge-cli create-package --bridges-dir ./generated \
--out-dir swifttest \
--macos target/debug/libswifttest.a \
--name swifttest
```
 The last command works and creates the framework, but I seem to be unable to use it (meaning if I drag it into Xcode I can't use it, which worked when I created one manually with cbindgen + xcodebuild). Also here I get `thread 'main' panicked at 'objc[XXXXX]`

<details markdown="1">
<summary>Backtrace</summary>

```sh
thread 'main' panicked at 'objc[53285]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1ffea3678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104a582c8). One of the two will be used. Which one is undefined.
objc[53285]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1ffea36c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104a58318). One of the two will be used. Which one is undefined.
', /Users/max/.cargo/registry/src/github.com-1ecc6299db9ec823/swift-bridge-build-0.1.29/src/package.rs:237:9
stack backtrace:
   0:        0x102a1a64c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h98d8e939df2a84c8
   1:        0x102a327a4 - core::fmt::write::ha8927896f8d44e8d
   2:        0x102a16e68 - std::io::Write::write_fmt::h5be52fc0ae77f963
   3:        0x102a1bafc - std::panicking::default_hook::{{closure}}::h7ab34c9d6fd8d067
   4:        0x102a1b6dc - std::panicking::default_hook::h6507a23c659c2199
   5:        0x102a1c13c - std::panicking::rust_panic_with_hook::h032de7ae9e9d479f
   6:        0x102a1bc88 - std::panicking::begin_panic_handler::{{closure}}::ha7b561c0fbbe4ae5
   7:        0x102a1ab0c - std::sys_common::backtrace::__rust_end_short_backtrace::h0ff1db7619f9e51e
   8:        0x102a1bbf0 - _rust_begin_unwind
   9:        0x102a3c78c - core::panicking::panic_fmt::h660aa0926f67c6d3
  10:        0x1029b9ba8 - core::panicking::panic_display::h2a32257c53f9b0b4
  11:        0x1029bbeac - swift_bridge_build::package::create_package::hb131d406ed7d47a3
  12:        0x1029b7bb8 - swift_bridge_cli::clap_exec::handle_matches::hf599b2bf43abb3b8
  13:        0x1029b921c - swift_bridge_cli::app::run::h8915dd2b0efc2cf1
  14:        0x1029b2fb8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8a0ea389a42ed100
  15:        0x1029b2f80 - std::rt::lang_start::{{closure}}::h6fc6137ebb093b3e
  16:        0x102a1a37c - std::rt::lang_start_internal::h35c587f98e9244f6
  17:        0x1029b2f64 - _main
```

</details>

For the test I do:
```sh
$ git clone git@github.com:chinedufn/swift-bridge.git && cd swift-bridge
$ cargo test --all && ./test-integration.sh
```
After updating my rust from 1.58 the tests worked but
```sh
Running `/Users/max/swift-bridge/target/debug/integration-test-create-swift-package`
```
still fails with the same panic message as above.

**Comment by chinedufn** [comment]
I'm seeing that you're only including a `--macos` target.

Are you trying to run it on an iOS or iOS simultor device?

---

It looks like line 237 is panicking here:

https://github.com/chinedufn/swift-bridge/blob/277e0f5ed9ae8e62b73dc2a21d87be4e5e828ecb/crates/swift-bridge-build/src/package.rs#L230-L238

It's possible that `xcodebuild` is writing a warning to `stderr` and that this isn't even a real error.

I think we should instead change this to something like:

```rust
    let output = Command::new("xcodebuild")
        .current_dir(&tmp_framework_path)
        .args(args)
        .spawn()
        .unwrap()
        .wait_with_output()
        .unwrap();
    if !output.success() {
        let stderr = std::str::from_utf8(&output.stderr).unwrap();
        panic!("{}", stderr);
    }
```

Want to give it a shot?

---

\cc @Jomy10 since he's familiar with this code

**Comment by chinedufn** [comment]
Looks like this is a known issue on M1s

https://developer.apple.com/forums/thread/698628

That thread makes it sound like it is indeed a warning and not an error. So, the code that I suggested above should hopefully fix it.

**Comment by Maxung** [comment]
So I modified the code to 

```Rust
let output = Command::new("xcodebuild")
        .current_dir(&tmp_framework_path)
        .args(args)
        .spawn()
        .expect("Failed to spawn xcodebuild")
        .wait_with_output()
        .expect("Failed to execute xcodebuild");
    if !output.status.success() {
        let stderr = std::str::from_utf8(&output.stderr).unwrap();
        panic!("{}", stderr);
    }
```
which leads to no more panics, but now the `swift test` part in `test_integration.sh` is failing:

```sh
objc[58964]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1ffea3678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107c502c8). One of the two will be used. Which one is undefined.
objc[58964]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1ffea36c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107c50318). One of the two will be used. Which one is undefined.
xcframework successfully written out to: /Users/max/swift-bridge/SwiftRustIntegrationTestRunner/swift-package-rust-library-fixture/MySwiftPackage/framework.xcframework
/Users/max/swift-bridge/SwiftRustIntegrationTestRunner/swift-package-rust-library-fixture/MySwiftPackage/Sources/MySwiftPackage/SwiftBridgeCore.swift:1:8: error: no such module 'Framework'
import Framework
       ^
/Users/max/swift-bridge/SwiftRustIntegrationTestRunner/swift-package-rust-library-fixture/MySwiftPackage/Sources/MySwiftPackage/SwiftBridgeCore.swift:1:8: error: no such module 'Framework'
import Framework
       ^

error: fatalError
```

I would be happy to submit a pull request with the/(your) fix, but maybe look at the new error at hand before doing  so (and regarding objc message, I also read that's most likely not an error but a warning)

**Comment by Maxung** [comment]
Also just for clarification (maybe I'm importing it wrong in Xcode) - Rust generates my package (including Package.swift). Under Xcode I go to add package, select the folder with the Package.swift and the .xcframework (+ Sources folder). Then I import with `import myname` and call `hello_rust()`?

**Comment by chinedufn** [comment]
@Maxung hmm integration tests seem to be passing in CI. I wonder if this is also an M1 issue.

But.. it looks like you're able to use your Swift Package now?

**Comment by Jomy10** [comment]
> hmm integration tests seem to be passing in CI. I wonder if this is also an M1 issue

This might be because the integration test used an x86_64 target in its test. But I’m not entirely sure.
