### ISSUE TITLE
Swiftc flags in Swift Package?

### ISSUE THREAD

**Issue by Jomy10** [chinedufn/swift-bridge#45]
I was wondering if we could replace this command: 

```
swiftc -L target/x86_64-apple-darwin/debug/ -lswift_and_rust -import-objc-header bridging-header.h \
  main.swift lib.swift ./generated/swift-and-rust/swift-and-rust.swift
```

with `swift build`

----

I have tried the following in `Package.swift`

```swift
// swift-tools-version:5.5

import PackageDescription

let package = Package(
    name: "LinuxSwiftPackage",
    dependencies: [],
    targets: [
        .executableTarget(
            name: "LinuxSwiftPackage",
            dependencies: [],
            linkerSettings: [
                .unsafeFlags(["-L lib_mac", "-lmy_rust_lib", "-import-objc-header bridging-header.h"])
            ]
        )
    ]
)
```

It didn't seem to work, though.

All settings can be found in the [Apple documentation](https://developer.apple.com/documentation/swift_packages/buildsettingcondition), there is [CSettings](https://developer.apple.com/documentation/swift_packages/csetting), [SwiftSettings](https://developer.apple.com/documentation/swift_packages/swiftsetting), [LinkerSettings](https://developer.apple.com/documentation/swift_packages/linkersetting), ...

These are all things we can specify in the `Package.swift`.

[here](https://theswiftdev.com/the-swift-package-manifest-file/#target) you can also find some information under "Settings".

----

[It looks like you can also specify a `json` file](https://forums.swift.org/t/compiler-flags-in-package-swift/11668/3) using `swift build --destination file.json`. This also looks like a promising option.

I tried `swift build --destination file.json`
```json
// file.json
{
    "version": 1,
    "sdk": "/swift/usr/bin/swift",
    "toolchain-bin-dir": "/swift/usr/bin",
    "target": "x86_64-apple-macosx",
    "dynamic-library-extension": "lib",
    "extra-cc-flags": [
    ],
    "extra-swiftc-flags": [
        "-L lib_mac",
        "-lmy_rust_lib",
        "-import-objc-header",
        "bridging-header.h"
    ],
    "extra-cpp-flags": []
}
```

but I'm getting
```swift
error: no such module 'Foundation'
import Foundation
```

----

This would allow us to link our library more easily in executable Swift packages, which I think would be useful for Linux as an alternative for generating a Swift Package.

I can't seem to find any more information on this and I'm not really knowledgeable in linking header files.

**Comment by Jomy10** [comment]
If you want to take a look at the package I used for this (currently has the json setup): https://github.com/Jomy10/swift-build-test

**Comment by chinedufn** [comment]
You're talking about in the swiftc + Cargo docs? https://github.com/chinedufn/swift-bridge/blob/ee8b26973e29411e8f53c87442acdd1b3cce6fc1/book/src/building/swiftc-and-cargo/README.md

> It didn't seem to work, though.

What was the problem?

> This would allow us to link our library more easily in executable Swift packages, which I think would be useful for Linux as an alternative for generating a Swift Package.

Can you elaborate on this use case? How does it look for users? What is the alternative right now?

> error: no such module 'Foundation'

What OS are you building this on?

**Comment by Jomy10** [comment]
> You're talking about in the swiftc + Cargo docs?

Yes

> What was the problem?

It would give me `cannot find type <SomeType defined in the SwiftBridgeCore header> in scope`, so the library was not actually being linked.

> Can you elaborate on this use case? How does it look for users? What is the alternative right now?

For Apple platforms, we currently have the xcframework implementation, but if we want to make an executable package for Linux that links to a Rust library, we need to use `swiftc`. The downside of this is that we can't use the Swift Package Manager to link dependencies to our executable.

> What OS are you building this on?

macOS (12)

**Comment by chinedufn** [comment]
Quick note: When sharing a repo I'd prefer if you included instructions to build from source instead of executables so that I don't have to run untrusted binaries.

---

Here's what I see.

```sh
$ swift build --destination file.json
<unknown>:0: warning: no such sysroot directory: '/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swift'
<unknown>:0: warning: no such sysroot directory: '/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swift'
<unknown>:0: error: unable to load standard library for target 'x86_64-apple-macosx10.10'
<unknown>:0: warning: no such sysroot directory: '/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swift'
<unknown>:0: error: unable to load standard library for target 'x86_64-apple-macosx10.10'
<unknown>:0: warning: no such sysroot directory: '/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swift'
<unknown>:0: error: unable to load standard library for target 'x86_64-apple-macosx10.10'
```

Looks like not everyone has the same sdk path

**Comment by chinedufn** [comment]
Seems like `swift build` doesn't let you use the unsafe linker flags to link in a static library https://stackoverflow.com/a/63070539

**Comment by Jomy10** [comment]
Hmmm, that's a shame. 

I haven't been able to find any more documentation/links regarding this either. It would've been nice. Maybe that's something that gets added in the future.

**Comment by chinedufn** [comment]
Closing this out since it doesn't seem to be possible. Looks like we'll have to wait for if/when Linux supports xcframework

**Comment by chinedufn** [comment]
Think I may have found something...

I took a look at the documentation in Swift packags

https://github.com/apple/swift-package-manager/blob/9274d1bf7dcd6ba14340121dc878a647c337ce08/Documentation/PackageDescription.md#product

I was able to generate a static library (`.a`) file by adding this to the products section of a Swift Package:

```
// swift-tools-version: 5.6
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "swift-library",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library( name: "swift-library", type: .static, targets: ["swift-library"]),
    ],
    // ... snippet ...
```
Note the `type: .static`

**Comment by lorenzolewis** [comment]
I have a friend who is using `swift build` in his implementation here: https://github.com/Brendonovich/swift-rs.

He has a build script that will link swift with Rust and then you can link a specific package. Under the hood I think it's just calling `swift build` (not sure on the compatibility with linux, though)

**Comment by lorenzolewis** [comment]
Here's the specific file: https://github.com/Brendonovich/swift-rs/blob/master/src-rs/build.rs

**Comment by Jomy10** [comment]
I think in an upcoming update of Swift it will be possible to have build scripts in a `Package.swift` file. Don’t know where I’ve read this, so I’ll keep an eye out for upcoming releases.
