### ISSUE TITLE
swift-bridge complains about String not being declared as type when trying to use borrowed Strings

### ISSUE THREAD

**Issue by cozyGalvinism** [chinedufn/swift-bridge#46]
Just stumbled over this:

![image](https://user-images.githubusercontent.com/1332113/158682174-23dabdd1-b2f1-43ef-a637-3e54532e6f73.png)

When trying to declare String as a type, swift_bridge then tells me that the String type is already supported.

**Comment by cozyGalvinism** [comment]
In fact, both examples dealing with references from [here](https://chinedufn.github.io/swift-bridge/built-in/string/index.html) return the same error.

**Comment by Jomy10** [comment]
I'm guessing this is either a bug, or it has not been implemented yet. I managed to recreate it locally as well. `&str` does not have this error, so in the meantime maybe you could use that.

<sub>P.S. May I ask what IDEA/extensions you use?<sub/>

**Comment by cozyGalvinism** [comment]
> P.S. May I ask what IDEA/extensions you use?
I use Visual Studio Code, with rust-analyzer and "Error Lens" (I have plenty more extensions installed, but these are the main ones you can see here). Some more Rust-related extensions I'm using are "Even Better TOML" (for TOML outline and hints), "Indent Rainbow" (for colored indents that make it obvious in what block I currently am), "Test Explorer UI" coupled with "Rust Test Explorer" (for unit tests)

**Comment by chinedufn** [comment]
Yup like @Jomy10 said the issue is that `&String` and `&mut String` haven't been implemented yet.
 
`fn make_ref_string(&self) -> &str` should work.

**Comment by cozyGalvinism** [comment]
Ah okay, I thought since it was documented that it was already in. Alright, I will use `&str` for now c:
