### ISSUE TITLE
Make `swift-bridge-build` write `SwiftBridgeCore` files alongside the library's bridges

### ISSUE THREAD

**Issue by chinedufn** [chinedufn/swift-bridge#49]
Right now `swift-bridge` writes `SwiftBridgeCore.h` and `SwiftBridgeCore.swift` to the `SWIFT_BRIDGE_OUT_DIR` during the `swift-bridge`crate's build script.

The problem with this is that if that build script doesn't run (say.. it already ran and then after it ran you deleted the auto generated files) you won't generate the `SwiftBridgeCore` files.

Instead.. when you use `swift_bridge_build` we should generate the core files alongside your library's bridge files.

This way you always get what you need when you build, as opposed to today's situation where you won't get the core files if `swift-bridge`'s build script doesn't run.

---

Once we solve this issue we can comment back in the CI job that was commented out in https://github.com/chinedufn/swift-bridge/pull/90

**Comment by jfaust** [comment]
Was this issue meant to be closed? The PR that closed it doesn't seem related.

**Comment by chinedufn** [comment]
Ah, nope. Thanks!

**Comment by chinedufn** [comment]
Closed via https://github.com/chinedufn/swift-bridge/pull/104
