### ISSUE TITLE
Support parameters for async functions and async methods

### ISSUE THREAD

**Issue by BenJeau** [chinedufn/swift-bridge#50]
Thanks for this crate! I'm looking into using `librespot` with Swift, but can't seem to have `async` methods or `async`  functions with parameters.

### `async` method

```rust
#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        type SpotifyApp;

        async fn connect(&mut self);
    }
}

pub struct SpotifyApp {}

impl SpotifyApp {
    pub async fn connect(&mut self) {
        print!("Connecting to Spotify...");
    }
}
```

```sh
error[E0425]: cannot find value `this` in this scope
 --> src/lib.rs:6:1
  |
6 | #[swift_bridge::bridge]
  | ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
  |
  = note: this error originates in the attribute macro `swift_bridge::bridge`
```

### `async` function with parameters

```rust
#[swift_bridge::bridge]
mod ffi {
    extern "Rust" {
        type SpotifyApp;

        async fn connect(track_id: &str);
    }
}

pub struct SpotifyApp {}

pub async fn connect(track_id: &str) {
    print!("Connecting to Spotify... {track_id}");
}
```

```sh
error[E0425]: cannot find value `track_id` in this scope
  --> src/lib.rs:11:26
   |
11 |         async fn connect(track_id: &str);
   |                          ^^^^^^^^ not found in this scope
```

Without one of these, I'm unable to pass data from the Swift app to Rust within `async` functions, do you think it is possible to have `async` methods or `async` functions with parameters? Thank you again :)

**Comment by BenJeau** [comment]
Or should I for now convert the `async` functions to non-async functions with `block_on` https://docs.rs/tokio/1.17.0/tokio/runtime/struct.Runtime.html#method.block_on and from the Swift side, create a new thread?

**Comment by chinedufn** [comment]
Hey Ben.

There's nothing preventing async methods from working, or preventing async methods/functions from taking args.

I just haven't implemented it yet.

I'd be more than happy to get this working for ya though.

Let me see if I can get taking arguments in async functions working tonight. 

Then I can take a look at getting async methods working tomorrow.

**Comment by chinedufn** [comment]
This commit makes arguments in async functions possible.

Now all we need is the ability to write async methods.

I'll take a look at that now.

**Comment by chinedufn** [comment]
This PR makes async methods possible -> https://github.com/chinedufn/swift-bridge/pull/52/files

> Or should I for now convert the async functions to non-async functions with block_on

That would also work, depending on your needs.

**Comment by chinedufn** [comment]
Thanks for opening this issue!

You can find support for async Rust functions and methods in `swift-bridge = "0.1.30"`

https://github.com/chinedufn/swift-bridge/releases/tag/0.1.30
https://crates.io/crates/swift-bridge

**Comment by BenJeau** [comment]
Thank you for the quick and fast work! I just tested it out and the async functions work, but as for the methods I get the following error

**Comment by chinedufn** [comment]
No problem!

Are you able to define a `struct MyTypeWrapper(Arc<Mutex<LibRespotType>>)` and then pass that over to Swift? At least for now?

I've opened https://github.com/chinedufn/swift-bridge/issues/58 to explore the idea of letting users control the async runtime. So feel free to subscribe to that issue and/or leave your own thoughts.

Solving this would let you just use a single threaded runtime in this case (I'm not sure if that's actually what you want.. but `swift-bridge` should at least make it an option..)
