### ISSUE TITLE
Support both ARM64 and x86-64 MacOS builds at once

### ISSUE THREAD

**Issue by mehcode** [chinedufn/swift-bridge#53]
If I supply `--macos target/aarch64-apple-darwin/debug/libmy.a` or `--macos target/x86_64-apple-darwin/debug/libmy.a` they work.

I'd like a way to supply both to build an XCFramework that'll work on the still supported and older Intel Macs.

**Comment by simlay** [comment]
If you do:
`lipo --macos target/aarch64-apple-darwin/debug/libmy.a target/x86_64-apple-darwin/debug/libmy.a -create -output ./target/universal/debug/libmy.a` and then `--macos ./target/universal/debug/libmy.a` you'll have both builds.

**Comment by mehcode** [comment]
Thank you
