### ISSUE TITLE
swift bridge test suite fails to compile

### ISSUE THREAD

**Issue by wtholliday** [chinedufn/swift-bridge#79]
To reproduce:

1. clone swift-bridge
2. git checkout 1951b4a262719c68590b635358677d1416248b58
3. cargo test --all && ./test-integration.sh

```
   Compiling hir_def v0.0.0 (https://github.com/rust-analyzer/rust-analyzer#c6995a37)
error[E0308]: mismatched types
  --> /Users/holliday/.cargo/git/checkouts/rust-analyzer-5e0f1308176aaeda/c6995a3/crates/hir_def/src/intern.rs:62:25
   |
62 |             None => Err(shard),
   |                         ^^^^^ expected struct `parking_lot::RawRwLock`, found struct `dashmap::RawRwLock`
   |
   = note: expected struct `lock_api::RwLockWriteGuard<'_, parking_lot::RawRwLock, HashMap<Arc<T>, SharedValue<()>, BuildHasherDefault<FxHasher>>>`
              found struct `lock_api::RwLockWriteGuard<'_, dashmap::RawRwLock, hashbrown::map::HashMap<Arc<T>, SharedValue<()>, BuildHasherDefault<FxHasher>>>`
```

```
rustc 1.60.0 (7737e0b5c 2022-04-04)
cargo 1.60.0 (d1fd9fe2c 2022-03-01)
macOS 12.3.1 (21E258)
Xcode  13.3.1 (13E500a)
```

**Comment by chinedufn** [comment]
Thanks for opening this. Sorry about that. Should work on the latest master branch. b068b596c81461ac48208af434567f1617d96a48

**Comment by wtholliday** [comment]
Ok I can get through all the tests now (`cargo test --all`) but `./test-integration.sh` fails if you don't have the archs installed. Perhaps it should run `rustup target add aarch64-apple-ios x86_64-apple-ios` ?

Afer installing the archs I get:

```
error: Build input file cannot be found: '/Users/[my username]/swift-bridge/SwiftRustIntegrationTestRunner/Generated/SwiftBridgeCore.swift' (in target 'SwiftRustIntegrationTestRunner' from project 'SwiftRustIntegrationTestRunner')
```

**Comment by chinedufn** [comment]
Can you `ls /Users/[my username]/swift-bridge/SwiftRustIntegrationTestRunner/Generated`? Is `SwiftBridgeCore.swift` in there?

I know Xcode can have this error when a file is first generated **during** the build process but did not exist before the build process started.

So if you see `SwiftBridgeCore.swift` in that directory then rerunning `./test-integration.sh` should work.

As to how to solve this going forward.. I guess a quick solution could be to `touch /Users/[my username]/swift-bridge/SwiftRustIntegrationTestRunner/Generated/SwiftBridgeCore.swift` in `./test-integration.sh` right before we run `xbodebuild` ..

This way the file exists before xcodebuild starts (and then gets overwritten with the real contents that we want during build process)

I'll make this change now.

**Comment by chinedufn** [comment]
Done https://github.com/chinedufn/swift-bridge/pull/80
