### ISSUE TITLE
trouble with CodegenVisualizer example

### ISSUE THREAD

**Issue by wtholliday** [chinedufn/swift-bridge#88]
Entitlements file seems to be missing (I added one)

Then getting

```
Generated/codegen-visualizer/codegen-visualizer.swift:36:24: error: initializer cannot be declared public because its parameter uses an internal type
    public convenience init(_ generated_code_holder: GeneratedCodeHolder) {
                       ^                             ~~~~~~~~~~~~~~~~~~~
/Users/holliday/swift-bridge/examples/codegen-visualizer/CodegenVisualizer/CodegenVisualizer/ContentView.swift:119:7: note: type declared here
class GeneratedCodeHolder: ObservableObject {
```

Xcode 13.3.1 (13E500a)

Does [.github/workflows/test.yaml ](https://github.com/chinedufn/swift-bridge/blob/master/.github/workflows/test.yml) test that example projects build with Xcode? I didn't see any lines of xcodebuild in there.

**Comment by chinedufn** [comment]
Ah. Sorry about that.

Good idea thank you. 

Fixed! https://github.com/chinedufn/swift-bridge/pull/89
